### ISSUE TITLE
Different numbers of # Epoch in output files

### ISSUE THREAD

**Issue by seanwong16** [mir-group/allegro#16]
Dear developers,

I found the epoch numbers in the output files are different in one training loop.

![image](https://user-images.githubusercontent.com/85958325/209913760-13812989-ea29-412c-83d6-deb915787778.png)

Is that normal and why does this happen ?

Thanks.
Sean

**Comment by Linux-cpp-lisp** [comment]
Hi @seanwong16 ,

Those epoch numbers are strange... can you elaborate on what you mean by "different in one training loop", and on what your setup us here?

**Comment by simonbatzner** [comment]
This looks like a filesystem issue with things writing at different times? Can you repro?

**Comment by simonbatzner** [comment]
Closing.
