### ISSUE TITLE
Neighbor lists in lammps-allegro

### ISSUE THREAD

**Issue by nicephore-bonnet** [mir-group/allegro#27]
Hello,
I have an issue in compiling Lammps with the Allegro patch, as I get the following error (with gcc):

_pair_allegro.cpp:129:33: error: ‘int LAMMPS_NS::NeighRequest::ghost’ is protected within this context
  129 |   neighbor->requests[irequest]->ghost = 1;_

I had to comment out this line in pair_allegro.cpp and hard-code ghost = 1 in neigh_request.cpp. It works, but probably not the best thing to do... (I think it then messes up with RDF calculations...)

Thanks for your help,

Nicephore

**Comment by Linux-cpp-lisp** [comment]
Duplicate of https://github.com/mir-group/pair_allegro/issues/17.

**Comment by nicephore-bonnet** [comment]
thanks!
