### ISSUE TITLE
Unable to open colab tutorial

### ISSUE THREAD

**Issue by APJansen** [mir-group/allegro#3]
On opening the colab tutorial I get an error: "There was an error loading this notebook. Ensure that the file is accessible and try again."

Other notebooks work fine (for example the nequip-tutorial), so I think it's not on my end.

I did find a workaround: opening in an incognito tab (chrome). So maybe it's something on my end after all, but I thought I'd post anyway just in case.

**Comment by simonbatzner** [comment]
Thanks for letting us know. It worked for me in different browsers. Which browser is this with?

**Comment by APJansen** [comment]
No problem, it's with chrome in non-incognito mode, the difference being probably that I'm not signed in to my google account in incognito mode.

**Comment by simonbatzner** [comment]
I’ll take a look, thank you for letting us know.

**Comment by simonbatzner** [comment]
Did you try this: https://stackoverflow.com/questions/48854737/google-colaboratory-and-google-drive-integration-fails

**Comment by APJansen** [comment]
Yes I don't have adblock and third party cookies are allowed. I removed all cookies and it worked once, but just because I wasn't signed in to my google account. I never had any issues with colab before.

**Comment by simonbatzner** [comment]
Hm I cannot reproduce this, I tried chrome + a different google account, still can view it in Chrome.

**Comment by APJansen** [comment]
Strange, I asked a colleague and she did have the same issue. Anyway thanks for looking into it, maybe wait to see if someone else independently runs into this before spending more time.

**Comment by PythonFZ** [comment]
I'm encountering the same issue using Firefox.

**Comment by simonbatzner** [comment]
Would you mind trying this link: https://colab.research.google.com/drive/1a0s34KERvJnvkdKSHkyG8HZYijC6xhwv#scrollTo=ZPqnt-SAXyvL

Sorry about this, all!

**Comment by PythonFZ** [comment]
> Would you mind trying this link: https://colab.research.google.com/drive/1a0s34KERvJnvkdKSHkyG8HZYijC6xhwv#scrollTo=ZPqnt-SAXyvL
> 
> Sorry about this, all!

Worked for me. Thanks!

**Comment by simonbatzner** [comment]
Updated the link in the REAMDE, thanks all.
