### ISSUE TITLE
how  can i conbine it with gromacs? 

### ISSUE THREAD

**Issue by InvincibleZZH** [mir-group/allegro#50]
in my own research, trajctories are generated from gromacs, is it possible to combine allegro with gromacs?

**Comment by JSLJ23** [comment]
Hi developers of Allegro, any updates on this? I am looking to run it within Gromacs and/or OpenMM as well.

**Comment by Linux-cpp-lisp** [comment]
Hi all,

Thanks for your interest in our work!

You can use trajectories or frames from any code as training data as long as you write up conversions into XYZ format (the `ase` library can help with this).

For running MD, we do not presently support GROMACS, but there has been work done on an integration into OpenMM that is available currently: https://github.com/mir-group/nequip/issues/288#issuecomment-1439034749.  This should provide a much greater level of immediate compatibility with a GROMACS based workflow than LAMMPS does.  However it is important to remember that LAMMPS remains our only 1st party MD integration for now, and is the only one currently that supports multi-GPU MD with Allegro.  (There is also an integration now with CP2K: https://www.cp2k.org/howto:allegro?s[]=allegro).
