### ISSUE TITLE
Best way to integrate virial and stress calculation with allegro?

### ISSUE THREAD

**Issue by yzjin** [mir-group/allegro#59]
There have been multiple attempts that aims at integrating the virial and stress into nequip and allegro: [nequip pull request](https://github.com/mir-group/nequip/pull/281), [pair-allegro stress branch](https://github.com/mir-group/pair_allegro/tree/stress), etc. However, I haven't found a comprehensive tutorial to integrate virial and stress calculation with the allegro model yet. I understand that the stress feature is under development, but if I would like to test with the existing features, which branch should I use for nequip, allegro and pair-allegro? Thanks in advance!

**Comment by Linux-cpp-lisp** [comment]
Hi @yzjin ,

Thanks for your interest in our work!

You should currently use the `develop` branch of `nequip`, any branch of Allegro, and pair_allegro [here](https://github.com/mir-group/pair_allegro/tree/multicut).
