### ISSUE TITLE
Training get slower with increasing epochs

### ISSUE THREAD

**Issue by zjgemi** [mir-group/allegro#60]
[almgcu.yaml.txt](https://github.com/mir-group/allegro/files/12924701/almgcu.yaml.txt)

When I trained the model on my own data (input config posted above, modified based on example.yaml), I found that as the number of epochs increases, the training process becomes slower and slower. The results in metrics_epoch.csv are as follows:

<img width="912" alt="截屏2023-10-17 下午1 51 10" src="https://github.com/mir-group/allegro/assets/27884723/14937f9e-48e1-4d36-8999-d3a44836addd">

Here, we can see that the first epoch took only ~1h, while the 8th epoch took ~8h. If I interrupt the training process and restart it, the first epoch after restarting takes about 1h again, but it gets slower and slower afterward. I'm not sure if I'm doing something wrong that's causing this strange behavior.

**Comment by Linux-cpp-lisp** [comment]
Hi @zjgemi ,

Thanks for your interest in our code!

This is a known issue related to the underlying PyTorch:  https://github.com/mir-group/nequip/discussions/311

Could you please report your PyTorch and CUDA versions, try the latest `nequip` `develop`, which may have a fix? 
After checking that I suggest you use one of the recommended PyTorch versions from the linked issue (https://github.com/mir-group/nequip/discussions/311) if possible.

**Comment by zjgemi** [comment]
My previous version was torch 2.0.0+cuda 11.7. When I switch to torch 1.11.0+cuda 11.3, the training speed increases significantly and no longer slows down as the number of epochs increases. Thank you!

**Comment by Linux-cpp-lisp** [comment]
Glad to hear @zjgemi .  Were you able to test whether the latest `develop` branch still exhibits the issue with PyTorch 2.0 on your system?
