### ISSUE TITLE
Activation parity

### ISSUE THREAD

**Issue by nec4** [mir-group/allegro#68]
Hello - thanks for developing and maintaining these tools!

I was looking at the nequip [full config](https://github.com/mir-group/nequip/blob/main/configs/full.yaml) and noticed the following options:

```
# scalar nonlinearities to use — available options are silu, ssp (shifted softplus), tanh, and abs.
# Different nonlinearities are specified for e (even) and o (odd) parity;
# note that only tanh and abs are correct for o (odd parity).
# silu typically works best for even 
nonlinearity_scalars:
  e: silu
  o: tanh

nonlinearity_gates:
  e: silu
  o: tanh
  ```

Are these options/parity differences applicable to Allegro models?

**Comment by Linux-cpp-lisp** [comment]
Hi @nec4 ,

Good question---these options are not relevant to the Allegro architecture, whose nonlinear activation functions are only in the MLPs, and are controlled by the various `*_mlp_nonlinearity` options such as https://github.com/mir-group/allegro/blob/main/configs/example.yaml#L71.

**Comment by nec4** [comment]
Thanks!

**Comment by nec4** [comment]
Hello - revisiting this again. Seems that `Tanh` is not a possible activation function to use in the config file. I understand SiLU is favored, but I want to use this activation for some extrapolative debugging purposes, where the choice of activation function can have a strong effect. 

Is it enough to just add a `torch.functional.tanh` in this dictionary [https://github.com/mir-group/allegro/blob/00b603867b5375adeb6ad4d556259b2bcaf74184/allegro/nn/_fc.py#L81C1-L84C36](url)? Or am I missing something else downstream?

**Comment by cw-tan** [comment]
Hi @nec4 , that should be all as far as I know. And I think `e3nn`'s `normalize2mom` should also just work for it, but worth bringing to your attention if you wanna sanity check that it doesn't do anything funny (https://github.com/e3nn/e3nn/blob/main/e3nn/math/_normalize_activation.py). Let us know if it works out!

**Comment by nec4** [comment]
Thanks so much for the quick response and helpful information!

**Comment by Linux-cpp-lisp** [comment]
@nec4 "extrapolative debugging purposes"---very interesting, and if you end up with some results on differences in extrapolation based on activation function we'd love to hear more or chat: [allegro-nequip@g.harvard.edu](mailto:allegro-nequip@g.harvard.edu).

**Comment by Linux-cpp-lisp** [comment]
@nec4  The only restrictions on nonlinearity are symmetric in `nequip`, where I think in the gate nonlinearities you can have _psuedo_scalar activation functions.  See https://github.com/mir-group/nequip/blob/main/nequip/nn/_convnetlayer.py#L42-L43. These must satisfy `f(-x) = -f(x)` (since the psuedoscalar flips sign on mirror flip of the system, and so the output of the activation function also must flip sign for its output to also be a psuedoscalar.  Since normal scalars are invariant to all symmetric transforms of E(3), any function taking a scalar produces one, and there is no restriction.)
