### ISSUE TITLE
Optimal hyper-parameters

### ISSUE THREAD

**Issue by chao1224** [mir-group/allegro#7]
Hi,
Thank you for providing the code base.
We want to reproduce your results, and we are wondering what are the hyper-parameters you are using for MD17 and QM9 respectively?
For MD17, you mentioned that it should be almost the same with [this example.yml file](https://github.com/mir-group/allegro/blob/main/configs/example.yaml) and  [nequip full.yml file](https://github.com/mir-group/nequip/blob/main/configs/full.yaml) right?

**Comment by Linux-cpp-lisp** [comment]
Hi @chao1224 ,

Thanks for your interest in our work!

Please see the methods section of our pre-print (https://arxiv.org/abs/2204.05249) which includes all of the hyperparameters used for the experiments in that manuscript.
